apiVersion: v1
kind: Service
metadata:
  name: dlc-standard-svc
  namespace: dlc
spec:
  selector:
    app: dlc-standard
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: webrtc
    port: 3478
    protocol: UDP
    targetPort: 3478
